stages:
  - install
  - test
  - build
  - deploy

image: node:18

variables:
  APP_NAME: angular-frontend-app
  ENV: staging

install_stage:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

test_stage:
  stage: test
  dependencies:
    - install_stage
  script:
    - echo "Running tests..."

build_stage:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - >
      echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}"
      > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "$CI_PROJECT_DIR"
      --dockerfile "$CI_PROJECT_DIR/Dockerfile"
      --destination "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
  artifacts:
    paths:
      - image.tar
    when: on_success


deploy_stage:
  stage: deploy
  script:
    - echo "Deploy step not implemented yet"
