stages:
  - install
  - test
  - build
  - deploy

image: node:latest # change "latest" later

variables:
  APP_NAME: angular-frontend-app
  ENV: staging

install_stage:
  stage: install
  artifacts:
    paths:
      - node_modules/
  script:
    - npm install

test_stage:
  stage: test
  dependencies:
    - install_stage
  script:
    - npm run test

build_stage:
  stage: build
  script:
    - docker build -t "$ENV-$APP_NAME" .

deploy_stage:
  stage: deploy
  script:
    - echo "not yet created"


